Issue1636
RTXteam/RTX pull request #1781
Opened 2022-01-31 21:31 UTC by rcpeene

Probably good to heavily review these changes, as they span many files and tests and something could have been missed.

2022-02-03 00:09 UTC, amykglen requested changes
awesome, thanks for doing this!!

just noticed a few issues where `biothings-explorer` is missing its `infores` prefix, but otherwise things look great to me.

when I run `pytest -v test_ARAX_expand.py --runslow --runexternal` I see the BTE-related tests failing - I imagine they should pass after adding in the `infores` prefix.

(note that some other 'external' tests are also failing when running the above command, but I suspect some of those may be failing in `master` too - may be worth checking just to confirm it wasn't due to changes in this issue)

2022-02-03 00:09 UTC, amykglen commented on code/ARAX/ARAXQuery/ARAX_expander.py
> +        "expand(edge_key=e00, kp=biothings-explorer)",
ope, should this be `kp=infores:biothings-explorer`?

2022-02-03 00:09 UTC, amykglen commented on code/ARAX/ARAXQuery/ARAX_query.py
> +            "expand(edge_key=e00, kp=biothings-explorer)",
also missing the `infores:` prefix I think? (i.e., `infores:biothings-explorer`?)

(looks like some more instances of this throughout the files too)

2022-02-04 22:24 UTC, rcpeene commented
Fixed the missing "infores" prefix for biothings explorer in multiple files at about 10 locations.

2022-02-15 23:03 UTC, amykglen approved these changes

2022-02-15 23:05 UTC, merged

2022-02-15 23:16 UTC, amykglen commented
just posting a comment to link this PR to #1636, so it's clear what changes were made for that issue