Added validation check in ARAX_expander.py:apply which checks if the …
RTXteam/RTX pull request #1866
Opened 2022-07-06 20:34 UTC by rcpeene

…given query graph has at least one pinned node

2022-07-07 16:41 UTC, amykglen commented
looks good to me! but as best practice before merging into `master`: I see the `issue1816` branch is pretty far behind `master` - can you merge `master` into `issue1816` (i.e., steps 4i-vi [here](https://github.com/RTXteam/RTX/wiki/Dev-info#dealing-with-pull-requests)), and then run the pytest suite to verify everything is passing?

2022-08-16 21:55 UTC, amykglen requested changes
see my comment on the PR about first merging `master` into your branch and making sure all tests are passing

2022-08-17 21:46 UTC, rcpeene commented
Have pulled from master, tested and made changes to one test. Should be good to merge now.

2022-08-18 21:10 UTC, amykglen approved these changes

2022-08-18 21:10 UTC, merged